#+TITLE: Introduction to Scrum
#+AUTHOR: Kyonax - Cristian Moreno

~First Definition~ to understand what is ~Scrum~ | *What is Agile Methodology?*

#+BEGIN_QUOTE
"Agile Methodology is a project management approach that prioritizes cross-functional collaboration and continuos improvement. It divides projects into smaller phases and guides teams through cycles of planning, execution, and evaluation."
#+END_QUOTE

* Table of Contents :toc:
- [[#notes][Notes]]
  - [[#what-is-agile-methodology][What is Agile Methodology?]]
- [[#principles-of-the-agile-manifesto][Principles of the Agile Manifesto]]
- [[#what-is-scrum][What is Scrum?]]
  - [[#scrum-essence][Scrum essence]]
  - [[#scrum-theory][Scrum theory]]
  - [[#scrum-pilars][Scrum Pilars]]

* Notes
** What is Agile Methodology?
Definition of some terms, and explanation of the Agile Methodology.
- *What is Agile?:*
  #+BEGIN_QUOTE
  "Agile is the hability to create products and respond to changes."
  "Agile is a set of frameworks and methodologies."
  #+END_QUOTE
- *Methodologies:*
  - Scrum
  - Kanban
  - XtremeProgramming
  - Pair to Pair Programming
  - Test Driven Development
- *Agile focus on people*
- *Agile Mindset*:
  #+BEGIN_QUOTE
  "We are discovering better ways of developing software, both through our own experience and by assisting others."
  #+END_QUOTE
- *Differences between Traditional Development and Agile*:
  - Team Work
  - Requirements
  - Value Generation

* Principles of the Agile Manifesto
#+BEGIN_QUOTE
1. "Our highest priority is to satisfy the customer through early and continuous delivery of valuable software."
2. "Welcome changing requirements, even late in development. Agile processes harness change for the customer's competitive advantage."
3. "Deliver working software frequently, from a couple of weeks to a couple of months, with a preference to the shorter timescale."
4. "Business people and developers must work together daily throughout the project."
5. "Build projects around motivated individuals. Give them the environment and support they need, and trust them to get the job done."
6. "The most efficient and effective method of conveying information to and within a development team is face-to-face conversation."
7. "Working software is the primary measure of progress."
8. "Agile processes promote sustainable development. The sponsors, developers, and users should be able to maintain a constant pace indefinitely."
9. "Continuous attention to technical excellence and good design enhances agility."
10. "Simplicity--the art of maximizing the amount of work not done--is essential."
11. "The best architectures, requirements, and designs emerge from self-organizing teams."
12. "At regular intervals, the team reflects on how to become more effective, then tunes and adjusts its behavior accordingly. "
#+END_QUOTE

Phrases to have in mind!
- "*Individuals and Interactions* over processes and tools."
- "*Working Software* over extensive documentations."
- "*Collaboration with the customer* over contractual negotiation."
- "*Responding to change* over following a plan."

* What is Scrum?
SCRUM definition, and why is important for the Agile Methodologies.

#+BEGIN_QUOTE
"SCRUM" is an ordered formation of players, used to restart play, in which the forwards of a team form up with arms interlocked and heads down, and push forward against a similar group from the opposing side. The ball is thrown into the "SCRUM" and the players try to gain posession of it by kicking it backwards towards their own side.
#+END_QUOTE

What is SCRUM for the Agile Methodologies

#+BEGIN_QUOTE
"SCRUM" is an agile team collaboration framework commonly used in Software Development and other industries. Scrum prescribes for team to break work into goals to be completed within time-boxed iterations, called "sprints" Each sprint is no longer than one month and commonly lasts two weeks. The Scrum team assesses progress in time-boxed, stand-up meetings of up to 15 minutes, called daily scrums.
#+END_QUOTE

** Scrum essence
The essence of Scrum is a small team of people. The individual team is flexible and adaptive.

- Ideal size of a team: min 3 (5-7 people) max 10
- Iterative Process

** Scrum theory
Scrum is based on the theory of empirical process control or empiricism. Empiricism ensures that knowledge comes from experience and making decisions based on what is known.

** Scrum Pilars
